import { Device, SensorReading, SensorHardware, AutomationRule, AlertNotification, EnergyBreakdown } from '../types';

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev_light_living',
    name: 'Living Room Light',
    room: 'Living Room',
    type: 'light',
    state: true,
    mode: 'AUTO',
    powerWatts: 14,
    lastUpdated: 'Just now',
  },
  {
    id: 'dev_light_bedroom',
    name: 'Bedroom Light',
    room: 'Master Bedroom',
    type: 'light',
    state: false,
    mode: 'MANUAL',
    powerWatts: 10,
    lastUpdated: '12m ago',
  },
  {
    id: 'dev_fan_main',
    name: 'Ceiling Fan',
    room: 'Living Room',
    type: 'fan',
    state: true,
    mode: 'AUTO',
    powerWatts: 55,
    lastUpdated: 'Just now',
  },
  {
    id: 'dev_plug_kitchen',
    name: 'Smart Plug',
    room: 'Kitchen Corner',
    type: 'plug',
    state: true,
    mode: 'MANUAL',
    powerWatts: 120,
    lastUpdated: '4m ago',
  },
];

export const INITIAL_SENSORS: SensorReading[] = [
  {
    id: 'sens_temp',
    sensorType: 'temperature',
    name: 'TEMPERATURE',
    value: 24.6,
    unit: '°C',
    status: 'OPTIMAL',
    history: [22.1, 22.8, 23.4, 24.0, 24.2, 24.6, 24.6],
    timestamp: 'Live stream',
  },
  {
    id: 'sens_humidity',
    sensorType: 'humidity',
    name: 'HUMIDITY',
    value: 58,
    unit: '%',
    status: 'NORMAL',
    history: [64, 62, 60, 59, 58, 57, 58],
    timestamp: 'Live stream',
  },
  {
    id: 'sens_motion',
    sensorType: 'motion',
    name: 'MOTION',
    value: 'SECURE',
    unit: '',
    status: 'SECURE',
    history: [0, 0, 1, 0, 0, 0, 0],
    timestamp: 'Live stream',
  },
  {
    id: 'sens_gas',
    sensorType: 'gas',
    name: 'GAS / SMOKE',
    value: 'NORMAL',
    unit: '180 ppm',
    status: 'NORMAL',
    history: [160, 172, 168, 175, 180, 178, 180],
    timestamp: 'Live stream',
  },
  {
    id: 'sens_light',
    sensorType: 'light',
    name: 'LIGHT LEVEL',
    value: 72,
    unit: '%',
    status: 'OPTIMAL',
    history: [45, 52, 60, 68, 70, 71, 72],
    timestamp: 'Live stream',
  },
  {
    id: 'sens_energy',
    sensorType: 'energy',
    name: 'CURRENT ENERGY',
    value: 1.8,
    unit: 'kW',
    status: 'NORMAL',
    history: [1.2, 1.4, 1.6, 1.9, 1.7, 1.8, 1.8],
    timestamp: 'Live stream',
  },
];

export const HARDWARE_MODULES: SensorHardware[] = [
  {
    id: 'hw_dht',
    code: 'DHT11 / DHT22',
    name: 'Temperature & Humidity',
    description: 'Capacitive humidity sensor & thermistor measuring ambient climate with 0.1°C precision via 1-wire digital bus.',
    category: 'Climate Perception',
    pin: 'GPIO 4',
    interfaceType: 'Single-Bus Digital',
    accentColor: '#FECCD3',
  },
  {
    id: 'hw_pir',
    code: 'PIR (HC-SR501)',
    name: 'Pyroelectric Motion',
    description: 'Passive infrared sensor detecting infrared radiation radiating from moving warm bodies across 120° field of view.',
    category: 'Spatial Security',
    pin: 'GPIO 13',
    interfaceType: 'Digital HIGH/LOW',
    accentColor: '#FFE500',
  },
  {
    id: 'hw_mq2',
    code: 'MQ-2 Gas / Smoke',
    name: 'Combustible & Smoke',
    description: 'SnO2 sensitive layer detecting LPG, Propane, Hydrogen, Carbon Monoxide, and airborne methane particles.',
    category: 'Hazard Prevention',
    pin: 'GPIO 34 (ADC1)',
    interfaceType: 'Analog & Comparator DO',
    accentColor: '#45C5E2',
  },
  {
    id: 'hw_ldr',
    code: 'LDR Optical Sensor',
    name: 'Ambient Light Level',
    description: 'Cadmium-Sulfide photo-resistor providing variable resistance tied to room ambient illumination lux.',
    category: 'Environmental Lux',
    pin: 'GPIO 35 (ADC1)',
    interfaceType: 'Analog Voltage Divider',
    accentColor: '#E6E0FF',
  },
  {
    id: 'hw_relay',
    code: '5V Optocoupler Relay',
    name: 'Galvanic Appliance Switch',
    description: 'Optically isolated electromagnetic relay board rated up to 10A 250VAC for air conditioning, lighting & motors.',
    category: 'Actuation Output',
    pin: 'GPIO 18, 19, 21, 22',
    interfaceType: 'Active-LOW Opto-Isolated',
    accentColor: '#FECCD3',
  },
];

export const INITIAL_RULES: AutomationRule[] = [
  {
    id: 'rule_1',
    name: 'High Thermal Relief',
    condition: 'IF TEMPERATURE > 30°C',
    action: 'TURN FAN ON',
    ifField: 'temperature',
    ifOperator: '>',
    ifValue: '30°C',
    thenDevice: 'Ceiling Fan',
    thenAction: 'ON',
    enabled: true,
  },
  {
    id: 'rule_2',
    name: 'Motion-Activated Welcome',
    condition: 'IF MOTION DETECTED',
    action: 'TURN LIGHT ON',
    ifField: 'motion',
    ifOperator: 'DETECTS',
    ifValue: 'Activity',
    thenDevice: 'Living Room Light',
    thenAction: 'ON',
    enabled: true,
  },
  {
    id: 'rule_3',
    name: 'Toxic Gas Lockdown',
    condition: 'IF GAS LEVEL IS HIGH (>300ppm)',
    action: 'TRIGGER SAFETY ALERT',
    ifField: 'gas',
    ifOperator: '>',
    ifValue: '300 ppm',
    thenDevice: 'Alarm Buzzer & Vent',
    thenAction: 'TRIGGER ALERT',
    enabled: true,
  },
  {
    id: 'rule_4',
    name: 'Twilight Illumination',
    condition: 'IF ROOM IS DARK (<30% lux)',
    action: 'TURN LIGHT ON',
    ifField: 'light',
    ifOperator: '<',
    ifValue: '30%',
    thenDevice: 'Living Room Light',
    thenAction: 'ON',
    enabled: false,
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt_gas',
    type: 'GAS',
    title: 'GAS HAZARD ALERT',
    message: 'Elevated hydrocarbon/smoke threshold detected in kitchen node (290 ppm). Emergency vent armed.',
    severity: 'CRITICAL',
    timestamp: 'Today at 02:44 AM',
    resolved: false,
  },
  {
    id: 'alt_motion',
    type: 'MOTION',
    title: 'UNEXPECTED MOVEMENT',
    message: 'PIR node #03 triggered in Living Room while in Armed Guard Mode.',
    severity: 'WARNING',
    timestamp: 'Yesterday at 11:18 PM',
    resolved: true,
  },
  {
    id: 'alt_temp',
    type: 'TEMPERATURE',
    title: 'THERMAL THRESHOLD CROSSED',
    message: 'Ambient temperature reached 30.8°C. Automated cooling relay initiated via rule #1.',
    severity: 'INFO',
    timestamp: 'Yesterday at 04:30 PM',
    resolved: true,
  },
];

export const ENERGY_BREAKDOWN: EnergyBreakdown[] = [
  { category: 'Lighting Modules', percentage: 42, kwh: 0.76, color: '#45C5E2' },
  { category: 'Cooling & Fan', percentage: 31, kwh: 0.56, color: '#FFE500' },
  { category: 'Smart Appliances', percentage: 27, kwh: 0.48, color: '#FECCD3' },
];
